name: dex-operator
version: 0.14.1
description: "An operator that automates the management of dex connector configurations"
appVersion: 0.14.1
home: "https://github.com/giantswarm/dex-operator"
icon: https://s.giantswarm.io/app-icons/dex/2/icon_light.svg
apiVersion: v1
annotations:
  application.giantswarm.io/team: "shield"
  config.giantswarm.io/version: 1.x.x
