name: dex-operator
version: 0.15.0
description: "An operator that automates the management of dex connector configurations"
appVersion: 0.15.0
home: "https://github.com/giantswarm/dex-operator"
icon: https://s.giantswarm.io/app-icons/dex/2/icon_light.svg
apiVersion: v1
annotations:
  io.giantswarm.application.audience: giantswarm
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
